{{ $myDict := dict "name1" "value1" "name2" "value2" "name3" "value 3" }}
{{- define "mychart.sugar.types"}}
  sugarTypes: |-
    - "brown"
    - "white"
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  {{- template "mychart.labels" . }}
data:
  messageFromChild: {{ .Values.message }}
  myvalue: "Hello World"
  {{- $relname := .Release.Name -}}
  {{- with .Values.favorite }}
  release: {{ $relname }}
  drink: {{ .drink | default "tea" | quote }}
  food: {{ .food | upper | quote }}  
  myDic: {{ get $myDict "name1" }}
  {{- if eq $.Values.favorite.drink "coffee" }}
  mug: "true"
  {{- end }}
  toppings: |-
    {{- range $index, $topping := $.Values.pizzaToppings }}
      {{ $index }}: {{ $topping }}
    {{- end }}  
  {{- end }}
  {{- range $key, $val := .Values.favorite }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- template "mychart.sugar.types" }}
  